"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['GECKOV.py']
DATA_FILES = ['neighbor', 'fitch','kitsch', 'forester.jar', '_aptx_configuration_file']
OPTIONS = {'argv_emulation': True, 'iconfile':'dna_mag.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
